syntax = "proto3";  // Указываем версию protobuf

package models;      // Имя пакета - будет соответствовать папке

option go_package = "github.com/Volpe1337/currency-service/subscriber/models";  // Куда генерировать Go код

// Сообщение, представляющее валюту
message Currency {
  string name = 1;    // Название валюты (например: "USD")
  string code = 2;    // Код валюты (например: "USD")
  double value = 3;   // Значение курса (например: 90.123)
}

// Сообщение для отправки нескольких валют
message CurrencyResponse {
  repeated Currency currencies = 1;  // Список валют
}